
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Check compatibility of two subtrees
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function isCompatible = compatible_subtrees( ...
    blockHierarchy, ...
    rowsA, ...
    rowsB, ...
    currentLevel, ...
    nLevels)
%COMPATIBLE_SUBTREES
% Return true when two blocks have identical nested structures,
% independent of their actual class or student labels.

    if numel(rowsA) ~= numel(rowsB)

        isCompatible = false;
        return;

    end

    if currentLevel > nLevels

        isCompatible = true;
        return;

    end

    signatureA = subtree_signature( ...
        blockHierarchy, ...
        rowsA, ...
        currentLevel, ...
        nLevels);

    signatureB = subtree_signature( ...
        blockHierarchy, ...
        rowsB, ...
        currentLevel, ...
        nLevels);

    isCompatible = strcmp( ...
        signatureA, ...
        signatureB);

end