%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Recursive helper
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function permIndex = recurse_block_level( ...
    blockHierarchy, ...
    targetRows, ...
    sourceRows, ...
    currentLevel, ...
    nLevels, ...
    permIndex, ...
    stream)
%RECURSE_BLOCK_LEVEL
% Randomly pair sibling source blocks with target blocks and
% recursively descend through the hierarchy.

    %% ======================================================
    % Leaf level
    %
    % After the final block level, randomly permute the
    % condition observations within the matched student block.
    %% ======================================================

    if currentLevel > nLevels

        if numel(targetRows) ~= numel(sourceRows)

            error( ...
                ['Target and source leaf blocks have ', ...
                 'different numbers of observations.']);

        end

        sourceOrder = randperm( ...
            stream, ...
            numel(sourceRows));

        permIndex(targetRows) = ...
            sourceRows(sourceOrder);

        return;

    end


    %% ======================================================
    % Identify child blocks at the current hierarchy level
    %% ======================================================

    targetBlockIDs = unique( ...
        blockHierarchy(targetRows, currentLevel), ...
        'stable');

    sourceBlockIDs = unique( ...
        blockHierarchy(sourceRows, currentLevel), ...
        'stable');

    nTargetBlocks = numel(targetBlockIDs);
    nSourceBlocks = numel(sourceBlockIDs);

    if nTargetBlocks ~= nSourceBlocks

        error( ...
            ['Target and source parent blocks contain ', ...
             'different numbers of children at level %d.'], ...
            currentLevel);

    end


    %% ======================================================
    % Randomize source sibling blocks
    %% ======================================================

    sourceOrder = randperm( ...
        stream, ...
        nSourceBlocks);

    sourceBlockIDs = ...
        sourceBlockIDs(sourceOrder);


    %% ======================================================
    % Pair target blocks with randomized source blocks
    %% ======================================================

    for b = 1:nTargetBlocks

        targetBlockID = ...
            targetBlockIDs(b);

        sourceBlockID = ...
            sourceBlockIDs(b);

        targetChildRows = targetRows( ...
            blockHierarchy(targetRows, currentLevel) ...
            == targetBlockID);

        sourceChildRows = sourceRows( ...
            blockHierarchy(sourceRows, currentLevel) ...
            == sourceBlockID);

        if ~compatible_subtrees( ...
                blockHierarchy, ...
                targetChildRows, ...
                sourceChildRows, ...
                currentLevel + 1, ...
                nLevels)

            error( ...
                ['Incompatible blocks were matched at ', ...
                 'hierarchy level %d.'], ...
                currentLevel);

        end

        permIndex = recurse_block_level( ...
            blockHierarchy, ...
            targetChildRows, ...
            sourceChildRows, ...
            currentLevel + 1, ...
            nLevels, ...
            permIndex, ...
            stream);

    end

end

