%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Recursive hierarchy validation
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function validate_parent_structure( ...
    blockHierarchy, ...
    parentRows, ...
    currentLevel, ...
    nLevels)
%VALIDATE_PARENT_STRUCTURE
% Recursively verify that all sibling blocks under a parent
% have identical subtree signatures.

    if currentLevel > nLevels
        return;
    end

    childIDs = unique( ...
        blockHierarchy(parentRows, currentLevel), ...
        'stable');

    childSignatures = strings( ...
        numel(childIDs), ...
        1);

    childRowsList = cell( ...
        numel(childIDs), ...
        1);

    for i = 1:numel(childIDs)

        childRows = parentRows( ...
            blockHierarchy(parentRows, currentLevel) ...
            == childIDs(i));

        childRowsList{i} = childRows;

        childSignatures(i) = subtree_signature( ...
            blockHierarchy, ...
            childRows, ...
            currentLevel + 1, ...
            nLevels);

    end

    if numel(unique(childSignatures)) ~= 1

        error( ...
            ['Sibling blocks at hierarchy level %d do not ', ...
             'have identical subtree structures.'], ...
            currentLevel);

    end

    for i = 1:numel(childIDs)

        validate_parent_structure( ...
            blockHierarchy, ...
            childRowsList{i}, ...
            currentLevel + 1, ...
            nLevels);

    end

end
